### PR TITLE
Add Arabic translations

### PR DESCRIPTION
**Pull request by hishamco**
Just I need to complete some missing translations and make some else better, BTW some terminologies are hard to translate it into Arabic ;)

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks a lot for your PR! 🎉 

> BTW some terminologies are hard to translate it into Arabic

Yeah, it's sometimes hard to find appropriate translations. If you think specific terms like "identity token" or "access token" don't have a reasonable equivalent in Arabic or if you feel their equivalent sounds too weird, don't hesitate to leave them in English if it's more appropriate.

**Comment by kevinchalet** [comment]
Out of curiosity, what tool did you use? The format seems a bit different to the one generated by the XLIFF tools.

**Comment by hishamco** [comment]
> if you feel their equivalent sounds too weird, don't hesitate to leave them in English if it's more appropriate.

Exactly!!

> Out of curiosity, what tool did you use? The format seems a bit different to the one generated by the XLIFF tools.

I used **Loco** https://localise.biz/free/poeditor, BTW there are some issues with the old IDs

**Comment by kevinchalet** [comment]
> I used Loco https://localise.biz/free/poeditor, BTW there are some issues with the old IDs

Yeah, it causes a merge conflict. Could you please rebase your branch on top of `dev`?

**Comment by hishamco** [comment]
Don't worry I will try to fix this today ...

**Comment by hishamco** [comment]
@kevinchalet it's DONE from my side

**Comment by kevinchalet** [comment]
Thanks a lot for your contribution, @hishamco! 👏

**Pull request merged**
