### PR TITLE
Ranamed OpenIddictContext to OpenIddictDbContext

### PR DESCRIPTION
**Pull request by xperiandri**
Ranamed OpenIddictContext to OpenIddictDbContext to correspond to ASP.NET Identity style and make name more meaningful

### CODE REVIEW

**Comment by Bartmax** [comment]
In case this is ok, readme must also be updated to mention `OpenIddictDbContext`. @PinpointTownes  ?

**Comment by xperiandri** [comment]
Updated

**Comment by kevinchalet** [comment]
@Bartmax if you're fine with this change, I'll merge it :+1:

**Comment by Bartmax** [comment]
LGTM :shipit:

**Comment by kevinchalet** [comment]
Merged, thanks! https://github.com/openiddict/openiddict-core/commit/fd7420c445eb147466fa31c7fbdb495399c32700

@xperiandri please consider sending a PR to fix Sean's sample: https://github.com/capesean/openiddict-test. It's a quite popular sample ;)

**Pull request closed without merging**
