### PR TITLE
Switch over from MSSQL to sqlite for the AspNetCore sandbox server

### PR DESCRIPTION
**Pull request by atrauzzi**

### CODE REVIEW

**Comment by kevinchalet** [comment]
While you're at it, can you please also replace SQL Server by SQLite in the `OpenIddict.Sandbox.AspNetCore.Client` project? Once it's replaced, you should be able to remove this line:

https://github.com/openiddict/openiddict-core/blob/fd6d074f6e0e22e716e80a9123af0512083fe7c2/Directory.Packages.props#L353

**Comment by atrauzzi** [comment]
@kevinchalet - Done!

**Review by kevinchalet — APPROVED** [review]
Thanks for your PR and congrats for your first contribution to OpenIddict, @atrauzzi! 🎉

**Comment by atrauzzi** [comment]
Yay yay yay!

**Pull request merged**
