### PR TITLE
Custom keys for MongoDB.

### PR DESCRIPTION
**Pull request by SebastianStehle**
Hi,

I created a feature request a while ago: https://github.com/openiddict/openiddict-core/issues/1242

I tried to solve it by making the key generic so that I can replace it with a string instead.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I was testing the sample, but the client cannot connect due to SSL issues. How do you handle this?

**Comment by SebastianStehle** [comment]
Hi,

I am using this in production since 2 months now and it is working fine. Any chance we can get it through? Do you want me to do any improvements or refactorings?

**Comment by kevinchalet** [comment]
Hi @SebastianStehle,

As part of the 4.0 effort, I'm actually evaluating a few other options, including the creation of "delegating" stores that would be able to wrap one or multiple stores and unify their results. I suspect this may suit your original need (without requiring to hack the MongoDB stores to share Ids with EntityFramework 😄)

I'll keep you informed.

**Comment by kevinchalet** [comment]
Sorry for not getting back to you earlier.

> As part of the 4.0 effort, I'm actually evaluating a few other options, including the creation of "delegating" stores that would be able to wrap one or multiple stores and unify their results. I suspect this may suit your original need (without requiring to hack the MongoDB stores to share Ids with EntityFramework 😄)

I discussed this option with a few OpenIddict users that could have been potentially interested in using such an option and we came to the conclusion that it could never be as flexible as custom stores. As such, it's unlikely that investing resources/time to have that directly in OpenIddict would make a lot of sense.

Having custom stores that exactly match your needs - as you did - remains the best option.

Closing.

**Comment by SebastianStehle** [comment]
Hi, can we talk about this again? I am still maintaining my own fork here and would like to prevent that.

**Comment by kevinchalet** [comment]
> Hi, can we talk about this again?

Certainly, but AFAICT, you're still the only one asking for such a feature. If I could dedicate an infinite amount of time to my OSS projects, I'd of course implement all the cool things folks ask for, but the truth is my resources are limited and given the limited number of people that would use this feature, it's very hard to justify spending time implementing and maintaining it.

That said, I'll definitely keep an eye on this thread to see if there are more people interested 👍🏻

**Comment by SebastianStehle** [comment]
I would like to care about the implementation. Therefore the PR, but I understand the point about maintaining...

**Pull request closed without merging**
