### PR TITLE
Use CryptoHelper.StrongName

### LINKED ISSUE #492: Strong name signing issue
Hello,

adding OpenIddict packages to an ASP.NET Core 2 application, that is signed with an .snk key, causes a **strong name validation failed** exception since the OpenIddict assemblies are not fully signed. 
Is it possible to sign the assemblies in future releases?

Thanks,

### PR DESCRIPTION
**Pull request by henkmollema**
Resolves #492

### CODE REVIEW

**Comment by kevinchalet** [comment]
Awesome, thanks!

Do you plan to also add a strong-named version of `2.0.0` (that targets `Microsoft.AspNetCore.Cryptography.KeyDerivation 1.0.0`)? It's the version used by OpenIddict 1.x.

**Comment by kevinchalet** [comment]
@henkmollema :ping_pong:

**Comment by henkmollema** [comment]
Yeah I will do that in a bit. I'll let you know.

**Comment by kevinchalet** [comment]
Thanks! OpenIddict RC2 is shipping this week (today or tomorrow) so let's do that for the next milestone.

**Comment by henkmollema** [comment]
I'm planning to do it in the next 2 hours or so. Perhaps it can make RC2?

**Comment by kevinchalet** [comment]
> Perhaps it can make RC2?

Sure.

**Comment by kevinchalet** [comment]
@henkmollema out of curiosity, did you take a look at the sources packages? The cool thing with that is that you wouldn't have to care about the versions of the ASP.NET Core packages since the package would only contain the .cs files of CryptoHelper (the ASP.NET Core version would be chosen by OpenIddict).

Here's a concrete example: https://dotnet.myget.org/F/aspnetcore-dev/api/v2/package/Microsoft.Extensions.CommandLineUtils.Sources/2.1.0-preview2-30045

**Comment by henkmollema** [comment]
@PinpointTownes I understand the concept of source packages. However I've not looked at utilizing it for CryptoHlper, I might look into for the next release.

**Comment by henkmollema** [comment]
I've uploaded a [v2.0.2](https://www.nuget.org/packages/CryptoHelper.StrongName/2.0.2) package which targets .NET Standard 1.0 and uses the ASP.NET Core 1.x packages. I'll send a PR in a sec.

**Comment by henkmollema** [comment]
Derp, need to add .NET 4.5.1 target as well. I'd hope these days were behind us now. 😿

**Comment by kevinchalet** [comment]
Haha, sorry for that. I still have a bunch of customers stuck on 1.0 and that's why I keep developing an 1.0-compatible version of OpenIddict 😅 

Another one of those viral things.

**Comment by henkmollema** [comment]
I understand. I've been struggling with it myself too. Last two years were messy, haha. 😄 

Anyways, just uploaded a new package. PR will be there in a bit.

**Comment by henkmollema** [comment]
@PinpointTownes see #553

**Comment by kevinchalet** [comment]
Awesome, thanks! :clap:

**Pull request merged**
