### PR TITLE
Updated XML documentation to correspond to ASP.NET Identity style

### PR DESCRIPTION
**Pull request by xperiandri**
For Entities the proposed order of properties is:
1. Id
2. Simple properties
3. Navigation properties

### CODE REVIEW

**Comment by kevinchalet** [comment]
As said on Gitter, I'm not convinced the proposed changes really make the XML documentation clearer and I'm even tempted to say a few changes are obscure (e.g https://github.com/openiddict/openiddict-core/pull/141/files#diff-bc597b8640c65721e968bcf03626cd84R14) or just wrong (e.g https://github.com/openiddict/openiddict-core/pull/141/files#diff-ad5de1b200d78d6645c213e895e4641bR17)

/cc @ilmax

**Comment by xperiandri** [comment]
@PinpointTownes, could you explain within inline comments, please.

**Comment by xperiandri** [comment]
?

**Comment by kevinchalet** [comment]
Since this PR doesn't really improve the existing code base, I'm closing it for now. Let's focus on your other PR instead.

**Comment by xperiandri** [comment]
> Since this PR doesn't really improve the existing code base

It is a matter of opinion :)

**Pull request closed without merging**
