### PR TITLE
Add KakaoTalk to the list of supported providers

### PR DESCRIPTION
**Pull request by steveberdy**

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks for your PR! Do you confirm it worked fine during your tests?

Note: I'm not familiar with Kakao's services, but I see on their website that they have multiple offerings. Should we update the name to be less specific (e.g `Kakao`) or match the name of the login service (`KakaoLogin`)?

**Comment by kevinchalet** [comment]
@steveberdy FYI, OpenIddict 4.7 is expected to ship next week. If your PRs are merged by then, the new providers will be part of 4.7. Otherwise they'll likely be included in the next release, 4.8, planned for September or October 😃

**Comment by steveberdy** [comment]
I changed it now. It should all be good now; there isn't much to this provider.

**Review by kevinchalet — APPROVED** [review]
Looks good. I'll add the ASCII art header and merge it with the other PRs when they are ready.

**Comment by kevinchalet** [comment]
Merged. Congrats for your first contribution to OpenIddict! 😍

**Pull request merged**
