### PR TITLE
The Story Is That I'm Making Multiency System Like Abp

### PR DESCRIPTION
**Pull request by cursor-background-agent-01**
And I Maked DbContext Named

AppDbContext

```c#
public class AppDbContext : DbContext
{
      public Tenant CurrentTenant { get; }
      public AppDbContext(Session session)
      {
            CurrentTenant = session.Tenant; // Here I Get Tenant From Claims And I Have TenantId In Claims
      }
      public void OnModelCreating(ModelBuilder builder)
      {
           // some business about connection string
      }
}
```

```c#
builder.AddDbContext<AppDbContext>(e =>
{
         e.UseSqlServer("none");
});
```

Here When Going To Openiddict The Host Db Work
But When Login From Tenant It Says Authorization Not Found And Some Times Application Not Found

So The ConnectionString Of The Host Is
"Server=.;Database=hostDb" And I Seed Data Into It

But In Tenant The Connection String Is Not The Same
"Server=.;Database=tenant1Db" Here Authorization Not Same
Cause Authorization Added Into Host

And After It He Checks The In tenant1Db

So What I Do 

```c#
// This Is In AddOpeniddict
builder.UseEntityFrameowrk()
     .UseDbContext(() => new AppDbContext(new Session(null))); // Here I Get The TenantId
     // When CurrentTenant Is Null I Make Host ConnectionString So This Is The Only Way
```

About The Additional Things I Added Is To Make It More And More Flexible For Other Developer

## I Don't Care To Be Contributor I Just Want To Complete My Website

### CODE REVIEW

**Comment by kevinchalet** [comment]
The scenario you describe is very common and you don't need any extra hook to implement it: https://github.com/openiddict/openiddict-core/pull/1884#issuecomment-1727404758.

**Comment by cursor-background-agent-01** [comment]
I Don't Understand

**Comment by cursor-background-agent-01** [comment]
It's Because The AppDbContext Is Injected By TenantId From Claims

**Comment by kevinchalet** [comment]
https://learn.microsoft.com/en-us/ef/core/miscellaneous/multitenancy

**Comment by cursor-background-agent-01** [comment]
This Because I Maked Each Database Can Contains Many Tenants
And You Can Make For Each Tenant A Database

**Comment by cursor-background-agent-01** [comment]
I Has Big App Thats Been Like Abp

Editions
Tenants
Users
Roles
And Others

**Comment by kevinchalet** [comment]
Again, you don't need a new hook to support that: you can resolve any service you need from your `DbContext` constructor, including a tenant service that can retrieve the tenant details from any place you want.

Anyway, this repository is not the right place for generic questions about EF Core: consider posting your question on StackOverflow if you still need help.

**Pull request closed without merging**
