### PR TITLE
Add Italian translations

### PR DESCRIPTION
**Pull request by ilmax**

### CODE REVIEW

**Comment by kevinchalet** [comment]
Thanks a lot for your contribution! 👏

**Comment by kevinchalet** [comment]
@ilmax please let me know when the PR can be merged 😃

**Comment by ilmax** [comment]
@kevinchalet let me re-review that today and then we are good to go

**Comment by ilmax** [comment]
@kevinchalet I think this is good to go, do you want me to rebase it and squash the commits?

**Comment by kevinchalet** [comment]
Merged, thanks a lot for your contribution, @ilmax! 👏 🎉

**Pull request merged**
