### PR TITLE
updated the Entity Framework Db Context registration with the updated…

### PR DESCRIPTION
**Pull request by orlaqp**
… syntax

### CODE REVIEW

**Comment by kevinchalet** [comment]
FYI, the commit is not bound to your GitHub account. You're likely using a different email address than the one stored in your local git configuration. Send me your GitHub email address by PM if you want me to fix your commit for you when merging it.

**Comment by orlaqp** [comment]
I am going to check my email address but it should be: (removed)

**Comment by kevinchalet** [comment]
The email associated with the commit is: `orlando@nova**********.com` (I obfuscated it :smile:)

**Comment by kevinchalet** [comment]
Note that you can also add this email address in the GitHub options, so it will be automatically recognized.

**Comment by orlaqp** [comment]
I did not know that, thanks!!

**Comment by kevinchalet** [comment]
Merged, thanks: https://github.com/openiddict/openiddict-core/commit/5838c24a85681a3d92f1b003b47b46cf6dfebb66 :clap: 

(FYI: I amended your commit to also update the Mvc.Server sample to use the new syntax)

**Pull request closed without merging**
